### ISSUE TITLE
Feature: typescript variables

### ISSUE THREAD

**Issue by fvdnabee** [promptfoo/promptfoo#1023]
Currently the evaluator supports [javascript and python variables](https://github.com/promptfoo/promptfoo/blob/7f3137d6f48b8f968befb4d199cda957a64d8275/src/evaluator.ts#L122). This issue requests to add typescript variables as a third option.

**Comment by typpo** [comment]
I think this would be quite difficult to do, given the different ways that typescript can be configured.  Since typescript is compiled, it's probably easiest to point it to the js file in your build or dist directory.

The only exception to this may be some of the alternative js runtimes that have native ts support.

**Comment by mldangelo** [comment]
@fvdnabee this is working now! Feel free to re-open if you have any questions. Check out our ts example here: https://github.com/promptfoo/promptfoo/tree/main/examples/ts-config
