### ISSUE TITLE
Using CSV tests with multiple columns

### ISSUE THREAD

**Issue by BrenosmMaia** [promptfoo/promptfoo#1708]
I was checking the [google sheets example](https://github.com/promptfoo/promptfoo/tree/main/examples/google-sheets) and saw that the CSV uses two input columns to the prompt file.

Can this be done with prompts from a python file?

I was only able to successfully run `promptfoo eval` with a single argument function, like
```
def challenging_prompt(deciding_rule) -> str:
    
    return f"Describe the rule {deciding_rule}" 
```

When I added a new argument, like

```
def challenging_prompt(deciding_rule, extra) -> str:
    
    return f"Describe the rule {deciding_rule}, considering {extra}" 
```

Got error
```
 Error running Python script: TypeError: challenging_prompt() missing 1 required positional argument: 'ex'
Stack Trace: Error: TypeError: challenging_prompt() missing 1 required positional argument: 'extra'
```

Using the CSV
| deciding_rule | extra | __expected |
|---------------|-------|------------|
| too_many_tries | new_user | dummy |

I'm not sure whether this is currently a limitation or if I'm not using it correctly.

**Comment by mldangelo** [comment]
Hi @BrenosmMaia,

Good question! The issue you're encountering is due to how promptfoo expects Python prompt functions to be structured. When using a Python prompt function with promptfoo, the function should accept a single `context` dictionary as its parameter. This `context` contains your test case variables and other useful information.

Here's how you can modify your function to work with multiple input variables:

```python
def challenging_prompt(context: dict) -> str:
    deciding_rule = context['vars']['deciding_rule']
    extra = context['vars']['extra']
    return f"Describe the rule {deciding_rule}, considering {extra}"
```

Your CSV file should have columns matching the variable names:

```
deciding_rule,extra,__expected
too_many_tries,new_user,dummy
```

For more details, please refer to the [promptfoo documentation on prompt functions](https://www.promptfoo.dev/docs/configuration/parameters/#prompt-functions). Let me know if this resolves your issue or if you have any more questions!

**Comment by BrenosmMaia** [comment]
@mldangelo 

Thanks! Issue solved.
