### ISSUE TITLE
Add support for Plug'n'Play

### ISSUE THREAD

**Issue by pedrooa** [promptfoo/promptfoo#1852]
**Is your feature request related to a problem? Please describe.**
After the release `0.72.0` promptfoo stopped supporting Plugnplay. It fails to start with the error message:
```
Error: promptfoo tried to access @inquirer/editor, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

**Describe the solution you'd like**
Install promptfoo via yarn using pnp - which is the direction the ecosystem is going.

**Describe alternatives you've considered**
The problem can be circumvented by using the traditional node_modules approach, but that breaks other pieces of my project and could introduce potential errors in the future with ghost dependencies.

**Comment by mldangelo** [comment]
Thank you, @pedrooa, for your quick solution on Discord! For anyone else facing the issue, here’s the solution:

To resolve the problem with Plug'n'Play (PnP) and `promptfoo`:

1. Update your `yarn` configuration to use `nodeLinker`:

   ```bash
   yarn config set nodeLinker node-modules
   yarn
   ```

This will switch from using Plug'n'Play to the traditional `node_modules` approach, which resolves the issue with missing dependencies for `@inquirer/editor`.

I’m closing this issue since we have a path forward. Thanks again for the solution! Thanks again @pedrooa
