### ISSUE TITLE
dry-run for cost estimation

### ISSUE THREAD

**Issue by hansujin93** [promptfoo/promptfoo#1864]
Is there a feature that allows for a dry run of the evaluation prior to execution? Considering that evaluations incur costs related to models and tokens, the ability to estimate approximate pricing through a dry run would offer valuable guidance for budgeting. If a dry run feature is not available, could you recommend alternative methods for price estimation? For instance, would integrating Langfuse, which clarifies how model pricing is determined based on model type/version and tokens/characters, be a viable option?

**Comment by mldangelo** [comment]
Hi @hansujin93, thanks for the suggestion! I think it's a great idea, but it's quite challenging to implement an accurate dry run cost estimator due to the variability in tokenization across different models. Since it's difficult to predict how many tokens an LLM call will consume beforehand, we likely won't support this feature in Promptfoo.

Check out [LiteLLM's cost estimator](https://docs.litellm.ai/docs/completion/token_usage), which does a great job of calculating token usage after you've made an API call. It might be helpful for your needs. Thanks again for the suggestion. 

Please feel free to post any other questions or issues you come across.
