### ISSUE TITLE
Can I run a GitHub action similarly on GitLab?

### ISSUE THREAD

**Issue by tttbone8122** [promptfoo/promptfoo#206]
I'm wondering if I can run what's here: https://www.promptfoo.dev/docs/integrations/github-action

But on GitLab?

**Comment by jamesbraza** [comment]
I think the answer out-of-the-box is no, but one can make this work using Docker ([read here](https://tomasvotruba.com/blog/how-can-we-use-github-actions-in-gitlab))

**Comment by typpo** [comment]
James is correct - it won't work out of the box on GitLab.  I've just added an example of a standalone github action here: https://github.com/promptfoo/promptfoo/blob/main/examples/github-action/standalone-action.yaml

This doesn't rely on the packaged action, and will be easier to convert to GitLab CI.  I'm guessing GPT-4 could do this with some degree of accuracy, since the formats are pretty similar.
