### ISSUE TITLE
AWS Bedrock anthropic.claude-3-5-sonnet-20241022-v2:0

### ISSUE THREAD

**Issue by sam86ni** [promptfoo/promptfoo#2322]
**Is your feature request related to a problem? Please describe.**
using the provider Bedrock im unable to use the latest Sonnet version 'bedrock:anthropic.claude-3-5-sonnet-20241022-v2:0'  the older version 'bedrock:anthropic.claude-3-5-sonnet-20240620-v1:0' works.  I have made sure to request access to the new version, which is approved on the account. 

There are two configurations i have tried, the diff is the id value for each:

**1).**
``` yaml
- id: "bedrock:anthropic.claude-3-5-sonnet-20241022-v2:0"
    config:
      region: 'us-east-1'
      temperature: 0.7
      max_tokens: 256
```

error: 
```
[FAIL] API call error: ValidationException: Invocation of model ID anthropic.claude-3-5-sonnet-20241022-v2:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains   │
│ this model.
```

**2).**
``` yaml
- id: "bedrock:us.anthropic.claude-3-5-sonnet-20241022-v2:0"
    config:
      region: 'us-east-1'
      temperature: 0.7
      max_tokens: 256
```

error:
```
[FAIL] Error: Unknown Amazon Bedrock model: us.anthropic.claude-3-5-sonnet-20241022-v2:0                                                                                                                                              │
│ Error: Unknown Amazon Bedrock model: us.anthropic.claude-3-5-sonnet-20241022-v2:0                                                                                                                                                     │
│     at getHandlerForModel (/opt/homebrew/lib/node_modules/promptfoo/dist/src/provi..
```

**Describe the solution you'd like**
I'd like to be able to use promptfoo for bedrock:anthropic.claude-3-5-sonnet-20241022-v2:0.  If anyone else has been successful, i'd appreciate some guidance.

**Describe alternatives you've considered**
No alternatives i can think of, i want to use the latest Sonnet to see if there's improvement with output

**Additional context**
I've also tested in a python app using langchain_aws with the model_id of 'us.anthropic.claude-3-5-sonnet-20241022-v2:0' which works.

**Comment by mldangelo** [comment]
@sam86ni Thanks for reporting this issue! This should now be fixed in version [0.100.6](https://github.com/promptfoo/promptfoo/releases/tag/0.100.6). 

The latest release also adds proper support for regional model identifiers in Bedrock. I've also updated our [AWS Bedrock documentation](https://www.promptfoo.dev/docs/providers/aws-bedrock/) to include how to properly format regional model identifiers and troubleshooting steps if a model isn't enabled in your region.

Please upgrade to v0.100.6 and let us know if you run into any other issues. Thanks for helping us improve promptfoo! 🙌
