### ISSUE TITLE
Implementing OpenAI assistants through node package

### ISSUE THREAD

**Issue by ajoublin** [promptfoo/promptfoo#310]
I'm trying to implement the node package using the OpenAI assistants.
The issue is that I can't manage to get my app working by setting the `apiKey` on my provider configuration.
I don't want to use environment variables so I try to use the `evaluate` function that way but the documentation is not clear enough.

Do you have any idea on how to achieve this ?

Here is the piece of my code :

```
const results = await promptfoo.evaluate(
        {
            env: {
                OPENAI_API_KEY: XXX,
            },
            prompts: prompts,//Assume this variable is set
            providers: ["openai:assistant:" + XXX],
        },
        {
            maxConcurrency: 1,
            progressCallback: (progress, total) => {
                console.log(`PROGRESS: ${progress} / ${total}`);
            },
        }
    );
```

And here is the error I get when executing this :
`Error: OpenAI API key is not set. Set the OPENAI_API_KEY environment variable or add `apiKey` to the provider config.`

**Comment by typpo** [comment]
Thanks for the report!  It looks like the current Assistants implementation is not correctly using the `apiKey` properties on the provider or env.  This is fixed in 6a5aab72f2b00fe650feeb1db7c41122e9958da9

The fix will be published in the next release.  Until then, you'd have to use environment variable (or clone & build the promptfoo repo manually).
