### ISSUE TITLE
Question: Output of tests and timeouts

### ISSUE THREAD

**Issue by JimBabcock59** [promptfoo/promptfoo#330]
This application is awesome. We have been using it for a few hours and it is a great productivity tool for what we do.

We did find 2 things that you may already have solutions for, but as newbes we could not find how to solve them in the documentation.

1 - with the web interface, it would be nice to be able to get the test results stored to a file in a computer readable format (maybe json). This would allow us to perform a higher level of analysis on them or to aggregate results from multiple sets of tests.

2 - for the ollama provider, it would be nice to have an optional setting that lets you set a maximum amount of time a particular prompt is allowed to run. Sometimes we know what the maximum amount of time we want to spend on a prompt. So once that time has elapsed, the test would be considered a failure.

Again thanks for creating a great tool.

**Comment by typpo** [comment]
Hi Jim,

Thanks for the kind words and I'm glad you're finding the tool useful!

1. By default, eval results are weritten to the `~/.promptfoo/output` directory in JSON format.  You may prefer to read these programmatically rather than using the webview (adding a download button to the webview is a good idea, though).

2. promptfoo supports a `REQUEST_TIMEOUT_MS` environment variable that can be overridden.  e.g. to set a 20-second limit
    ```
    REQUEST_TIMEOUT_MS=20000 promptfoo eval
    ```

**Comment by typpo** [comment]
Closing this one out.  Let me know if you have any more questions :)
