### ISSUE TITLE
Add support for Mistral.ai

### ISSUE THREAD

**Issue by streichsbaer** [promptfoo/promptfoo#448]
I saw that it's possible to use OpenRouter to run the mistral-medium model with promptfoo.

I have signed up for Mistral's `La Plateforme` and was making a custom provider work locally yesterday.

Is there any interest in adding native support?

If so, I'm happy to take a stab at it.

**Comment by typpo** [comment]
I definitely support adding Mistral!

If you've written the custom provider, you've done almost all the work already.  You'd have to add the `mistral:` prefix to [`providers.ts`](https://github.com/promptfoo/promptfoo/blob/main/src/providers.ts#L269-L271).  If you want to support caching, you can use [`fetchWithCache`](https://github.com/promptfoo/promptfoo/blob/main/src/cache.ts#L48) in your provider instead of regular `fetch`.

Let me know if you run into any issues - I'm also happy to help with this.

**Comment by streichsbaer** [comment]
Ok, I'll clean up the custom provider a bit and will create a PR.
