### ISSUE TITLE
Feature Request: Use Promptfoo to generate DPO datasets

### ISSUE THREAD

**Issue by streichsbaer** [promptfoo/promptfoo#449]
I use promptfoo a lot. It was the missing piece of a proper development stack for LLM-based applications.

As part of creating extensive evals, you get to compare a lot of different models with ease. That helps a lot with selecting the right model for a given task.

However, there will always be a goal to replace more expensive models with fine-tuned open-source alternatives.

Wouldn't it be great to take the existing data generated by running promptfoo to automatically create DPO datasets?

This could be as simple as using the UI to thumbs up one of the model responses per prompt.
Then all the ingredients should be pretty much there. The input system message/prompt, as well as a response pair with one response being marked as preferred.

Does that make sense?

**Comment by typpo** [comment]
Hey @streichsbaer,

#482 starts the work on this.  A couple areas where I'm seeking feedback
- I've made `chosen` and `rejected` string arrays rather than strings, because some users have multiple columns.  Does that make sense to you, or does it make ingesting this data more cumbersome?
- I am assuming that `system` and `question` are test case vars.  Does that match workflow?  I'm wondering if there is a better way to do this more generically.  I could just add the `vars` map to the object.

**Comment by streichsbaer** [comment]
Hi @typpo, thanks for that, and sorry for the late response.

- Strings should be fine for `chosen` and `rejected`, but having string arrays is ok too. The post-processing of this is not an issue.
- Correct, the `system` and `question` are the test case vars. Adding the vars map to the object is a good idea, then there is more flexibility in the post-processing steps.

**Comment by typpo** [comment]
This feature is released in [0.50.0](https://github.com/promptfoo/promptfoo/releases/tag/0.50.0).  Thanks and let me know if you have any more feedback!

![image](https://github.com/promptfoo/promptfoo/assets/310310/fd13001f-b9ff-4c43-86d3-512ca33c3441)

**Comment by streichsbaer** [comment]
Awesome, thanks @typpo 🙏
