### ISSUE TITLE
Prompt file doesn't support multi-shot, multi-line prompts 

### ISSUE THREAD

**Issue by liorn** [promptfoo/promptfoo#65]
I would like to give a multi-shot prompt with multiple user/assistant messages.
For that, as the examples state, I use a JSON list of objects.
However, in this format, if I have newlines inside a prompt, the JSON isn't properly decoded (as officially, newlines should be encoded as \n in JSONs).

This makes it extremely uncomfortable to use, as copying prompts in/out of promptfoo requires a lot of manual work of transforming newlines to \n s.

I think there should be a way to write multi-line, multi-shot prompts in some non-JSON way.

**Comment by liorn** [comment]
Sure! I would like something like this:
```
[{"role": "system", "content": "This is a multiline prompt.
It has multiple lines in it.
Today, it doesn't work."},
{"role": "user", "content": "Another prompt,
which has several lines in it."}]```

**Comment by typpo** [comment]
Ah I see.  As you pointed out in your original post, that is not valid JSON.  I imagine most users won't want a tool that coerces malformed JSON to correct JSON, because then it won't work properly in their production application.

One potential solution is to add YAML support.  YAML has built-in support for multiline strings, and it maps directly to JSON.  For example:
```yaml
- role: system
  content: |
    This is a multiline prompt.
    It has multiple lines in it.
    Today, it doesn't work.
- role: user
  content: |
    Another prompt,
    which has several lines in it.
```

What do you think?

**Comment by liorn** [comment]
That would make a lot of sense.

**Comment by typpo** [comment]
This will be in the next release.  Example usage here: https://github.com/promptfoo/promptfoo/tree/main/examples/openai-multiline-yaml

**Comment by liorn** [comment]
Thanks for the prompt fix (pun intended)!
