### ISSUE TITLE
Documentation for data structures GradingResult and ProviderResponse

### ISSUE THREAD

**Issue by efung** [promptfoo/promptfoo#769]
For the following structures, the documentation differs from what we've tested. Happy to make a PR to update the docs, if someone can confirm the following. I'm only using Python custom assertions and providers.

# GradingResult ([Typescript reference](https://www.promptfoo.dev/docs/configuration/reference/#gradingresult))
- `score` documented to be a `float` between 0 and 1, but we've been able to return a dictionary.
- `reason` is allowed to be `None` ( I guess `null` in Typescript)

# ProviderResponse ([Typescript reference](https://www.promptfoo.dev/docs/configuration/reference/#providerresponse))
- The [Python documentation](https://www.promptfoo.dev/docs/providers/python/#types) says that `output` must be `Optional[str]`.  However, the Typescript docs says it could also be a dictionary, and we confirmed that works in Python.

**Comment by typpo** [comment]
Thanks for catching these errors!

In the Typescript definition, [GradingResult](https://github.com/promptfoo/promptfoo/blob/main/src/types.ts#L340) expects a numeric `score` and a non-null `reason`.  We should treat that as the source of truth because the rest of the code depends on these types.  So I would consider this a validation issue in the Python provider (or maybe all dynamic providers like `exec` and `javascript` too).

For [ProviderResponse](https://github.com/promptfoo/promptfoo/blob/main/src/types.ts#L153), it does look like `output` can be an object.  So the Python docs are wrong.
