### ISSUE TITLE
Markdown appearing when manually failing test case

### ISSUE THREAD

**Issue by chrismaltais** [promptfoo/promptfoo#810]
When rendering with markdown in the web viewer, if I manually fail the test case (i.e. thumbs down), the markdown appears _and_ is rendered:

https://github.com/promptfoo/promptfoo/assets/17098959/a80c214c-511b-449e-aea8-eb45bab074cc

Is this intended? Would be nice if we _only_ rendered the markdown, similar to the success case

**Comment by chrismaltais** [comment]
https://github.com/promptfoo/promptfoo/assets/17098959/db302cbd-5810-4dd6-8e39-62697aee9afa

This no longer occurs as of version 0.61.0, closing!

**Comment by chrismaltais** [comment]
@typpo looks like this is issue is re-occurring in 0.62.0

Can we open up this issue again? 🙏

**Comment by mldangelo** [comment]
Hi @chrismaltais, this has been fixed in #5872 (v0.118.13). Thanks for reporting and following up when it regressed.

The root cause was fail reasons being prepended to output text, which then got rendered as markdown (causing the double display you saw). That's now been removed. Please feel free to open another issue or comment here if you run into anything else!
